language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods --pre # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/CDOAuth1Kit.xcworkspace -scheme CDOAuth1Kit-Example -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 7' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint