language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

cache: cocoapods
podfile: Example/Podfile

env:
global:
  - WORKSPACE="Example/CDOAuth1Kit.xcworkspace"
  - SCHEME="CDOAuth1Kit-Example"
matrix:
  - DESTINATION="platform=iOS Simulator,name=iPhone 7" SDK="iphoneos"
before_install:
- gem install cocoapods --pre # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace $WORKSPACE -scheme $SCHEME -sdk $SDK -destination $DESTINATION ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint