blank_issues_enabled: false
contact_links:
  - name: Usage Question
    url: https://stackoverflow.com/questions/tagged/cdoauth1kit
    about: Please ask usage questions on Stack Overflow using the `cdoauth1kit` tag.
  - name: Security Vulnerability
    url: mailto:contact@christopherdehaan.me
    about: Please report security vulnerabilities privately via email.
